### ISSUE TITLE
Incorrect result from greatest function

### ISSUE THREAD

**Issue by akhilg** [fentik/flink#12] opened 2022-09-14 23:36 UTC
The following query returns wrong results
```

WITH `prospect_person` AS (
    SELECT `person`.`id`, `person`.`team_id`
    FROM `source_25`.`person` AS `person`
    WHERE ((`person`.`sourced_timestamp` IS NOT NULL) AND `person`.id = 34349590 AND ((`person`.`is_anonymized` IS NULL) OR (`person`.`is_anonymized` <> TRUE))))
(SELECT `p`.`id` AS `person_id`,
             max(coalesce(t.logged_ts, 0)) as max_logged_ts,
             max(coalesce(lemfa.date_sent, 0)) as max_date_sent,
             max(coalesce(oosm.sent_timestamp, 0)) as sent_timestamp,
             max(coalesce(oorm.reply_timestamp, 0)) as reply_timestamp,
             greatest(max(coalesce(t.logged_ts, 0)),
                      max(coalesce(lemfa.date_sent, 0)),
                      max(coalesce(oosm.sent_timestamp, 0)),
                      max(coalesce(oorm.reply_timestamp, 0))) as greatest_g
FROM `prospect_person` AS `p`
LEFT JOIN `source_25`.`touchpoint` AS `t` ON (`t`.`person_id` = `p`.`id`)
LEFT JOIN `source_25`.`person_email` AS `pe` ON (`pe`.`person_id` = `p`.`id`)
LEFT JOIN `source_25`.`last_email_message_for_address` AS `lemfa` ON ((`lemfa`.`email` = `pe`.`email`) AND (`lemfa`.`team_id` = `p`.`team_id`))
LEFT JOIN `source_22`.`one_off_sent_message` AS `oosm` ON (`oosm`.`person_id` = `p`.`id`)
LEFT JOIN `source_22`.`one_off_reply_message` AS `oorm` ON (`oorm`.`one_off_sent_message_id` = `oosm`.`id`) GROUP BY p.id);

+----+-------------+-------------+-------------+-------------+-------------+-------------+
| op |   person_id |      EXPR$1 |      EXPR$2 |      EXPR$3 |      EXPR$4 |  greatest_g |
+----+-------------+-------------+-------------+-------------+-------------+-------------+
| +I |    34349590 |           0 |           0 |           0 |           0 |           0 |
| -D |    34349590 |           0 |           0 |           0 |           0 |           0 |
| +I |    34349590 |           0 |  1591921330 |           0 |           0 |           0 |
```

But, changing the order of argument to greatest (moving the non-zero value to the end), returns the right value

```
WITH `prospect_person` AS (
    SELECT `person`.`id`, `person`.`team_id`
    FROM `source_25`.`person` AS `person`
    WHERE ((`person`.`sourced_timestamp` IS NOT NULL) AND `person`.id = 34349590 AND ((`person`.`is_anonymized` IS NULL) OR (`person`.`is_anonymized` <> TRUE))))
(SELECT `p`.`id` AS `person_id`,
             max(coalesce(t.logged_ts, 0)),
             max(coalesce(lemfa.date_sent, 0)),
             max(coalesce(oosm.sent_timestamp, 0)),
             max(coalesce(oorm.reply_timestamp, 0)),
             greatest(max(coalesce(t.logged_ts, 0)),
                      max(coalesce(oosm.sent_timestamp, 0)),
                      max(coalesce(oorm.reply_timestamp, 0)),
                      max(coalesce(lemfa.date_sent, 0))) as greatest_g
FROM `prospect_person` AS `p`
LEFT JOIN `source_25`.`touchpoint` AS `t` ON (`t`.`person_id` = `p`.`id`)
LEFT JOIN `source_25`.`person_email` AS `pe` ON (`pe`.`person_id` = `p`.`id`)
LEFT JOIN `source_25`.`last_email_message_for_address` AS `lemfa` ON ((`lemfa`.`email` = `pe`.`email`) AND (`lemfa`.`team_id` = `p`.`team_id`))
LEFT JOIN `source_22`.`one_off_sent_message` AS `oosm` ON (`oosm`.`person_id` = `p`.`id`)
LEFT JOIN `source_22`.`one_off_reply_message` AS `oorm` ON (`oorm`.`one_off_sent_message_id` = `oosm`.`id`) GROUP BY p.id);

+----+-------------+-------------+-------------+-------------+-------------+-------------+
| op |   person_id |      EXPR$1 |      EXPR$2 |      EXPR$3 |      EXPR$4 |  greatest_g |
+----+-------------+-------------+-------------+-------------+-------------+-------------+
| +I |    34349590 |           0 |           0 |           0 |           0 |           0 |
| -D |    34349590 |           0 |           0 |           0 |           0 |           0 |
| +I |    34349590 |           0 |  1591921330 |           0 |           0 |  1591921330 |

```

**Comment by akhilg** [comment] 2022-09-14 23:39
@nparrish42 can you help write a test case in your regression suite and see if you can re-produce this in your environment - It will help us iterate on testing a potential.

No table other than last_email_message_for_address has a row that matches the join condition.

@sergeitsar I will need your help in figuring out where to start hunting for the bug - I am guessing it is in same file/code area as your previous bug - May bug you to get you on a call for a few minutes so that I can try to track it down - This is a blocker for Ben since it is returning incorrect results

**Comment by sergeitsar** [comment] 2022-09-14 23:47
We just landed. Can take a look later tonight. Should be faster to fix
since I’m more familiar with flink now. It’s definitely the same code I
touched and similar flavor bug with how the code generator declares local
variables.

**Comment by akhilg** [comment] 2022-09-14 23:57
Thanks - Ping me when you take a look at it. I can get online and give you
more context on when the bug shows up and when it doesn't. Working on
seeing if I can reproduce it in a dev environment without having to go to
production.

Akhil

**Comment by akhilg** [comment] 2022-09-15 00:22
I think I found the bug - @sergeitsar if you get a chance, take a look at this (already submitted to the rc1 branch)

https://github.com/fentik/flink/commit/b347733d82211b41fb0449658bfbca12fb644d8e

The earlier code would set nullTerm to true when it would encounter the first element that is not NULL. And, the skip comparing any elements that follow it (since nullTerm is True).

I suspect the logic you want is assume that the result is NULL (aka all input elements are NULL) and when we encounter the first non-null element, compare and store the greatest/least number.

**Comment by akhilg** [comment] 2022-09-15 00:31
Never mind - I was wrong (and have reverted the change). That logic is correct if you want to return NULL if any input is NULL (which is what greatest does (I made the mistake of thinking NULL is 0).

**Comment by sergeitsar** [comment] 2022-09-15 00:38
Try passing in a combination of constant values, column references and
expressions. Just a guess without looking at it.

Greatest(1, 3, somecol, somecol2, somecol +2, function())

My memory is fuzzy, but I remember the code generator had a couple of
different paths based on input parameter types.

**Comment by sergeitsar** [comment] 2022-09-15 01:25
I was able to steal a couple of minutes after dinner, here's a quick repro:

```
Flink SQL> select greatest(1, 1);

[ERROR] Could not execute SQL statement. Reason:
org.codehaus.commons.compiler.CompileException: Line 58, Column 42: Redefinition of local variable "tmpResult$13" 
```

The generated code is trying to define a temp variable twice: once as a primitive and once as a boxed type (lines 60 and 58 below). 

```
/* 57 */           // boxedResultTypeTerm tmpResult = {castIfNumeric(elements.head)}; 
/* 58 */           java.lang.Integer tmpResult$13 = ((int) 1);
/* 59 */           // primitiveResultTypeTerm result = {primitiveDefaultValue(widerType.get)};
/* 60 */           int result$13 = -1;
/* 61 */           if (!nullTerm$13) {
```

**Comment by sergeitsar** [comment] 2022-09-15 02:58
Ok, I'm going to back-out my original fix for greatest() which introduced this particular issue. To document the bug that exists in flink today a bit more (I didn't document this in the original bug and it took me a few moments to remember the issue).

Here's the simplest repro to trigger the original bug in the most egregious way:
```
Flink SQL> select
>   greatest(coalesce(oi.price, 0))
>   from source_1.order_items oi
> ;
+----+------------------------+
| op |                 EXPR$0 |
+----+------------------------+
[ERROR] Could not execute SQL statement. Reason:
java.lang.VerifyError: Expecting a stackmap frame at branch target 76
Exception Details:
  Location:
    StreamExecCalc$21.<init>([Ljava/lang/Object;Lorg/apache/flink/streaming/runtime/tasks/StreamTask;Lorg/apache/flink/streaming/api/graph/StreamConfig;Lorg/apache/flink/streaming/api/operators/Output;Lorg/apache/flink/streaming/runtime/tasks/ProcessingTimeService;)V @67: ifeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 2ab7 007d 2a12 7f10 1405 b800 83b5 0050
    0000010: 2abb 0040 5904 b700 85b5 003a 2abb 0028
    0000020: 5901 b700 87b5 006c 2a2b b500 8b2a 2b03
    0000030: 32c0 0052 b500 112a 2c2d 1904 b600 8f2a
    0000040: c100 1599 0009 2a19 05b6 0093 b1       
```

Here's the relevant bits of code generated by the planner so you can see the uninitialized variable read.

Quick guide:
 externalResult$18 is the result of the coalesce() function
 the generated code expects the result of coalesce to be in register tmpResult$20

However, if you trace the code below, you will see that 
`     result$19 = externalResult$18;`
comes AFTER
`    org.apache.flink.table.data.DecimalData tmpResult$20 = org.apache.flink.table.data.DecimalDataUtils.castToDecimal(result$19, 20, 2);
`

```
        @Override
        public void processElement(org.apache.flink.streaming.runtime.streamrecord.StreamRecord element) throws Exception {
          org.apache.flink.table.data.RowData in1 = (org.apache.flink.table.data.RowData) element.getValue();

          org.apache.flink.table.data.DecimalData field$16;
          boolean isNull$16;
          org.apache.flink.table.data.DecimalData externalResult$18;
          org.apache.flink.table.data.DecimalData result$19;
          boolean isNull$19;


          isNull$16 = in1.isNullAt(7);
          field$16 = null;
          if (!isNull$16) {
            field$16 = in1.getDecimal(7, 20, 2);
          }

          out.setRowKind(in1.getRowKind());




           org.apache.flink.table.data.DecimalData tmpResult$20 = org.apache.flink.table.data.DecimalDataUtils.castToDecimal(result$19, 20, 2);
           org.apache.flink.table.data.DecimalData result$20 = null;
           boolean nullTerm$20 = false;





          externalResult$18 = (org.apache.flink.table.data.DecimalData) function_org$apache$flink$table$runtime$functions$scalar$CoalesceFunction$081acce440d9567a963370b8fb1c1096
            .eval(isNull$16 ? null : ((org.apache.flink.table.data.DecimalData) field$16), false ? null : ((org.apache.flink.table.data.DecimalData) ((org.apache.flink.table.data.DecimalData) decimal$17)));

          isNull$19 = externalResult$18 == null;
          result$19 = null;
          if (!isNull$19) {
            result$19 = externalResult$18;
          }
```

**Comment by sergeitsar** [comment] 2022-09-15 13:29
Initialization of the input register happens inside of elements -> element -> code. The easiest fix is to add an initialization of the first input up before the assignment to the generator's initializer code.

Here' example contents of `${element.code}`:

```
          externalResult$18 = (org.apache.flink.table.data.DecimalData) function_org$apache$flink$table$runtime$functions$scalar$CoalesceFunction$081acce440d9567a963370b8fb1c1096
            .eval(isNull$16 ? null : ((org.apache.flink.table.data.DecimalData) field$16), false ? null : ((org.apache.flink.table.data.DecimalData) ((org.apache.flink.table.data.DecimalData) decimal$17)));

          isNull$19 = externalResult$18 == null;
          result$19 = null;
          if (!isNull$19) {
            result$19 = externalResult$18;
          }
```

**Closed** 2022-09-15 13:33 UTC

**Comment by nparrish42** [comment] 2022-09-15 21:37
@sergeitsar , just to be sure, your latest fix also addresses the original bug you describe in [this comment](https://github.com/fentik/flink/issues/12#issuecomment-1247519327)?  
your suggested repro runs OK now, and I've checked in some regression tests to dataflo/development which validate the fix, and these all pass as well.

**Comment by sergeitsar** [comment] 2022-09-15 23:34
Yeah, latest fix should fix both original issue and the issue gem saw.
